FROM node:20-slim
WORKDIR /app
COPY visualizer/package.json .
RUN npm install
COPY visualizer/ .
EXPOSE 3000
HEALTHCHECK --interval=10s --timeout=5s --retries=5 CMD curl -f http://localhost:3000
CMD ["node", "server.js"]